//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderstandingEFApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalary
    {
        public string id { get; set; }
        public Nullable<double> BAsic { get; set; }
        public Nullable<double> HRA { get; set; }
        public Nullable<double> Da { get; set; }
        public Nullable<double> Deductions { get; set; }
    }
}
